baseURL: "https://music_and_the_brain.jon-e.net/"
languageCode: en-us
title: Music and the Brain
theme: "ath-tufte-hugo_18-19"
googleAnalytics: ""
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - \.Rhistory$
  - \.yaml$
  - _files$
  - _cache$
  - \.csl$
  - \.Rproj.user/*
permalinks:
  post: "/:year/:month/:day/:slug/"
buildFuture: true
menu:
  main:
    - name: Syllabus
      url: /syllabus/
      weight: 1
    - name: Assignments
      url: /assignments/
      weight: 3
    - name: Schedule
      url: /schedule/
      weight: 2
    - name: Reference
      url: /reference/
      weight: 4
# Disable taxonomies
taxonomies:
  tag: ""
  group: ""
  category: ""
params:
  author: Jonny Saunders
  thumbnail: /images/stats_meta.png
  instructor: 
    name: Jonny Saunders
    email: jsaunder@uoregon.edu
    url: "https://jon-e.net"
    twitter: json_dirs
    github: sneakers-the-rat
    office: LISB 206
  course:
    number: PSY 348
    semester: Summer 2019
    days: "Monday-Thursday"
    time: "12:00-1:50PM"
    location: "Mackenzie 232"
    twitter: json_dirs
    dates: "June 24th - July 18th"
    github: "sneakers-the-rat/music_and_the_brain"
    copyrightYear: "2019"
    contactDetails: >-
      Office Hours: Monday, Wednesday 2:30-3:30
  university: 
    name: University of Oregon
    url: "https://www.uoregon.edu"
  school:
    name: Department of Psychology, Institute of Neuroscience
    url: "https://psychology.uoregon.edu/"
  description: "Music from acoustics to perception"
  primaryColor: "#D46600"
  secondaryColor: "#F6E03F"
  credits: >-
    Site design by Andrew Heiss.
  logo:
    url: /images/stats_hires.png
    alt: Data Science for Public Management
  meta:
    twitterSite: "@json_dirs"
    twitterCreator: "@json_dirs"
    fbAuthor: "https://www.facebook.com/jonny.saunders"
